{
 "title": "Gateway Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "gatewayDeployment",
    "label": "Gateway Deployment",
    "query": {
     "query": "process_runtime_jvm_system_cpu_load_1m{job!=\"\"}"
    }
   },
   {
    "name": "gatewayPod",
    "label": "Pod",
    "query": {
     "query": "process_runtime_jvm_system_cpu_load_1m{pod!=\"\",job=\"$gatewayDeployment\"}"
    }
   },
   {
    "name": "serviceName",
    "label": "Service Name",
    "query": {
     "query": "l7_service_attempted_count_total{l7_serviceName!=\"\", job=\"$gatewayDeployment\"}"
    }
   },
   {
    "name": "requestMethod",
    "label": "Request Method",
    "query": {
     "query": "l7_service_attempted_count_total{l7_method!=\"\",l7_serviceName=\"$serviceName\", job=\"$gatewayDeployment\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Gateway Service Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(l7_service_attempted_count_total{job=\"$gatewayDeployment\"}) ",
     "legendFormat": "{{podName}}"
    }
   ]
  },
  {
   "title": "Successful Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(l7_service_success_count_total{job=\"$gatewayDeployment\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Routing Failures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(l7_service_attempted_count_total{job=\"$gatewayDeployment\"} - l7_service_success_count_total{job=\"$gatewayDeployment\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Transaction Rate (Cluster[5m])",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(l7_service_attempted_count_total{job=\"$gatewayDeployment\"}[5m]))",
     "legendFormat": "${gatewayDeployment}"
    }
   ]
  },
  {
   "title": "Policy Violations",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "l7_service_policy_violations_count_total{job=\"$gatewayDeployment\"}",
     "legendFormat": "{{apiName}}"
    }
   ]
  },
  {
   "title": "Transactions Rate (Service[5m])",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(l7_service_attempted_count_total{l7_serviceName=\"$serviceName\",job=\"$gatewayDeployment\",l7_method=\"$requestMethod\"}[5m])",
     "legendFormat": "{{l7_serviceName}}"
    }
   ]
  },
  {
   "title": "Avg. Latency (milliseconds) $serviceName",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "l7_service_latency_milliseconds_sum{job=\"$gatewayDeployment\"} / l7_service_latency_milliseconds_count{job=\"$gatewayDeployment\"}",
     "legendFormat": "{{pod}}-{{l7_serviceName}}"
    }
   ]
  },
  {
   "title": "Service Latency Histogram",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, l7_service_latency_milliseconds_bucket{})",
     "legendFormat": "{{l7_serviceName}}"
    }
   ]
  },
  {
   "title": "Requests per service",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "l7_service_attempted_count_total{job=\"$gatewayDeployment\", l7_method=\"$requestMethod\"}"
    }
   ]
  },
  { "title": "Traces and Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Gateway Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "filters": [
      { "id": "b2be9011", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "query": "{.k8s.deployment.name=\"$gatewayDeployment\" && .k8s.pod.name=\"$gatewayPod\" && .l7_serviceName=\"$serviceName\"}",
     "spss": 3,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Gateway Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "{pod=\"$gatewayPod\", container=\"gateway\"} |= ``"
    }
   ]
  },
  {
   "title": "Gateway Application Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_runtime_jvm_system_cpu_utilization_ratio",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "System Load (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "process_runtime_jvm_system_cpu_load_1m",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage (non-heap)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_runtime_jvm_memory_usage_bytes{type=\"non_heap\"}",
     "legendFormat": "{{pod}}-{{pool}}-{{type}}"
    }
   ]
  },
  {
   "title": "Memory Usage (heap)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_runtime_jvm_memory_usage_bytes{type=\"heap\"}",
     "legendFormat": "{{pod}}-{{pool}}-{{type}}"
    }
   ]
  }
 ]
}